
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALWAYS AND ATOM EVENTUALLY IMPLIES LPAREN NEXT NOT OR RPAREN UNTILformula : ATOMformula : NOT formulaformula : formula AND formulaformula : formula OR formulaformula : formula IMPLIES formulaformula : NEXT formulaformula : ALWAYS formulaformula : EVENTUALLY formulaformula : formula UNTIL formulaformula : LPAREN formula RPAREN'
    
_lr_action_items = {'ATOM':([0,3,4,5,6,7,8,9,10,11,],[2,2,2,2,2,2,2,2,2,2,]),'NOT':([0,3,4,5,6,7,8,9,10,11,],[3,3,3,3,3,3,3,3,3,3,]),'NEXT':([0,3,4,5,6,7,8,9,10,11,],[4,4,4,4,4,4,4,4,4,4,]),'ALWAYS':([0,3,4,5,6,7,8,9,10,11,],[5,5,5,5,5,5,5,5,5,5,]),'EVENTUALLY':([0,3,4,5,6,7,8,9,10,11,],[6,6,6,6,6,6,6,6,6,6,]),'LPAREN':([0,3,4,5,6,7,8,9,10,11,],[7,7,7,7,7,7,7,7,7,7,]),'$end':([1,2,12,13,14,15,17,18,19,20,21,],[0,-1,-2,-6,-7,-8,-3,-4,-5,-9,-10,]),'AND':([1,2,12,13,14,15,16,17,18,19,20,21,],[8,-1,8,8,8,8,8,8,8,8,8,-10,]),'OR':([1,2,12,13,14,15,16,17,18,19,20,21,],[9,-1,9,9,9,9,9,9,9,9,9,-10,]),'IMPLIES':([1,2,12,13,14,15,16,17,18,19,20,21,],[10,-1,10,10,10,10,10,10,10,10,10,-10,]),'UNTIL':([1,2,12,13,14,15,16,17,18,19,20,21,],[11,-1,11,11,11,11,11,11,11,11,11,-10,]),'RPAREN':([2,12,13,14,15,16,17,18,19,20,21,],[-1,-2,-6,-7,-8,21,-3,-4,-5,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,3,4,5,6,7,8,9,10,11,],[1,12,13,14,15,16,17,18,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> ATOM','formula',1,'p_formula_atom','ltl_parser.py',46),
  ('formula -> NOT formula','formula',2,'p_formula_not','ltl_parser.py',50),
  ('formula -> formula AND formula','formula',3,'p_formula_and','ltl_parser.py',54),
  ('formula -> formula OR formula','formula',3,'p_formula_or','ltl_parser.py',58),
  ('formula -> formula IMPLIES formula','formula',3,'p_formula_implies','ltl_parser.py',62),
  ('formula -> NEXT formula','formula',2,'p_formula_next','ltl_parser.py',66),
  ('formula -> ALWAYS formula','formula',2,'p_formula_always','ltl_parser.py',70),
  ('formula -> EVENTUALLY formula','formula',2,'p_formula_eventually','ltl_parser.py',74),
  ('formula -> formula UNTIL formula','formula',3,'p_formula_until','ltl_parser.py',78),
  ('formula -> LPAREN formula RPAREN','formula',3,'p_formula_paren','ltl_parser.py',82),
]
